version: "3.5"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3305:3305"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
 
    portainer:
      image: portainer/portainer
      command: -H unix:///var/run/docker.sock
      restart: always
      ports:
        - 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
   
    watchtower:
      image: v2tec/watchtower
      container_name: watchtower-compose
      privileged: true
      command: watchtower clusterman clusterman --interval 30
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/config.json
    dbzabbix:
      image: gcavalcante8808/zabbix-db-postgres:4.0.0
      restart: always
      environment:
        POSTGRES_DB: zabbix
        POSTGRES_USER: zabbix
        POSTGRES_PASSWORD: "zabbix"
      volumes:
        - zabbix-db-data:/var/lib/postgresql/data

    server:
      image: gcavalcante8808/zabbix-server:4.0.0
      build: zabbix/server/
      restart: always
      environment:
        DB_HOST: dbzabbix
        DB_PORT: 5432
        DB_USER: zabbix
        DB_PASS: zabbix
        DB_NAME: zabbix
        DB_TYPE: POSTGRESQL
      # REALTIME EVENT EXPORT SUPPORT.
      # EVENT_EXPORT_DIR: /data
      # EVENT_EXPORT_FILESIZE: 100M
      volumes:
       - zabbix-server-conf:/usr/local/etc/zabbix_server.conf.d
       - zabbix-server-scripts:/usr/local/share/zabbix/external_scripts
     # REALTIME EVENT EXPORT SUPPORT.
     #- event-data:/data
      ports:
       - "10051:10051"
      depends_on:
       - dbzabbix

    frontend:
      image: gcavalcante8808/zabbix-frontend:4.0.0
      restart: always
      environment:
        DB_HOST: dbzabbix
        DB_PORT: 5432
        DB_USER: zabbix
        DB_PASS: zabbix
        DB_NAME: zabbix
        DB_TYPE: POSTGRESQL
        ZBX_SERVER: server
        ZBX_SERVER_PORT: 10051
        ZBX_SERVER_NAME: "Zabbix Docker"
      ports:
       - "8080:80"
      depends_on:
       - dbzabbix

volumes:
  persistent:
  portainer_data:
  zabbix-server-conf:
  zabbix-server-scripts:
  zabbix-db-data:
  zabbix-agentd-conf:
  zabbix-agentd-scripts:
    # REALTIME EVENT EXPORT SUPPORT.
    # event-data:

