version: '3'
volumes:
    zabbix-server-conf:
    zabbix-server-scripts:
    zabbix-db-data:
    zabbix-agentd-conf:
    zabbix-agentd-scripts:
    # REALTIME EVENT EXPORT SUPPORT.
    # event-data:

services:
  dbzabbix:
    image: gcavalcante8808/zabbix-db-postgres:4.0.0
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: "zabbix"
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

  server:
    image: gcavalcante8808/zabbix-server:4.0.0
    build: server/
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
      # REALTIME EVENT EXPORT SUPPORT.
      # EVENT_EXPORT_DIR: /data
      # EVENT_EXPORT_FILESIZE: 100M
    volumes:
     - zabbix-server-conf:/usr/local/etc/zabbix_server.conf.d
     - zabbix-server-scripts:/usr/local/share/zabbix/external_scripts
     # REALTIME EVENT EXPORT SUPPORT.
     #- event-data:/data
    ports:
     - "10051:10051"
    depends_on:
     - dbzabbix
  
  frontend:
    image: gcavalcante8808/zabbix-frontend:4.0.0
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
      ZBX_SERVER: server
      ZBX_SERVER_PORT: 10051
      ZBX_SERVER_NAME: "Zabbix Docker"
    ports:
      - "8082:80"
    depends_on:
     - dbzabbix



