version: '2'
volumes:
    proxy-conf:
    proxy-scripts:
    zabbix-agentd-conf:

services:
    agentd:
      image: gcavalcante8808/zabbix-agentd
      restart: always
      environment:
        ZBX_SERVER: proxy
        REMOTE_COMMANDS: 1
      volumes:
       - zabbix-agentd-conf:/usr/local/etc/zabbix_agentd.conf.d
        
    proxy:
      image: gcavalcante8808/zabbix-proxy
      restart: always
      environment:
        ZBX_SERVER: server
        ZBX_SERVER_PORT: 10051
      volumes:
       - proxy-conf:/usr/local/etc/zabbix_proxy.conf.d
       - proxy-scripts:/usr/local/share/zabbix
      ports:
        - "10051:10051"
